#!/bin/bash
# test_scenario5.sh - Kiểm thử Kịch bản 5: NAC / Captive Portal
# Mô tả:
#   1. hnew (host mới, chưa xác thực) kết nối vào mạng
#   2. Controller mặc định chỉ cho hnew kết nối đến Auth Server (10.0.0.200:8080)
#   3. hnew truy cập Auth Server để xác thực (POST /authenticate)
#   4. Auth Server thông báo Controller cấp quyền đầy đủ
#   5. hnew có thể truy cập toàn bộ mạng

echo "[KỊCH BẢN 5: NAC / Captive Portal - Xác thực Host mới]"
echo ""

HNEW_IP="10.0.0.50"
HNEW_MAC="00:00:00:00:00:50"
AUTH_IP="10.0.0.200"
AUTH_PORT="8080"
WEBSERVER_IP="10.0.0.100"
H2_IP="10.0.0.2"
SWITCH="s1"

echo "------------------------------------------------------------"
echo "[BƯỚC 1] Gửi gói đầu tiên từ hnew để Controller phát hiện Host mới"
echo ""
echo "Trong Mininet CLI:"
echo "  mininet> hnew ping -c 1 $AUTH_IP"
echo ""
echo ">>> Kết quả mong đợi trên log Controller (tail -f /tmp/dynamic_acl.log):"
echo "  [PacketIn] dpid=1 in_port=7 eth_src=00:00:00:00:00:50 ip_src=10.0.0.50"
echo "  [Controller] NAC RESTRICTED: eth_src=00:00:00:00:00:50 must authenticate"
echo "  [ACLManager] DROP MAC: in_port=7 eth_src=00:00:00:00:00:50 priority=10 on dpid=1"
echo "  [ACLManager] ALLOW HTTP AUTH: src_mac=00:00:00:00:00:50 dst=10.0.0.200:8080 priority=20"
echo ""

echo "------------------------------------------------------------"
echo "[BƯỚC 2] Xem flow table - kiểm tra luật hạn chế NAC..."
echo ""
echo "Lệnh:"
echo "  sudo ovs-ofctl dump-flows $SWITCH -O OpenFlow13"
echo ""
echo ">>> Kết quả mong đợi (xuất hiện luật DROP và luật ALLOW cụ thể):"
echo "  1. Chặn hnew: priority=10, in_port=7, eth_src=00:00:00:00:00:50 actions=drop"
echo "  2. Mở cổng Auth: priority=20, tcp, in_port=7, eth_src=00:00:00:00:00:50, nw_dst=10.0.0.200, tp_dst=8080 actions=NORMAL"
echo ""

echo "------------------------------------------------------------"
echo "[BƯỚC 3] Xác minh hnew bị hạn chế truy cập"
echo ""
echo "Trong Mininet CLI:"
echo "  mininet> hnew ping -c 3 $H2_IP"
echo "  >>> Kết quả mong đợi: FAIL (100% packet loss)"
echo ""
echo "  mininet> hnew curl -s --connect-timeout 2 http://$AUTH_IP:$AUTH_PORT/health"
echo "  >>> Kết quả mong đợi: SUCCESS ({\"status\": \"ok\"})"
echo ""

echo "------------------------------------------------------------"
echo "[BƯỚC 4] hnew thực hiện xác thực qua Auth Server"
echo ""
echo "Trong Mininet CLI:"
echo "  mininet> hnew curl -s -X POST http://$AUTH_IP:$AUTH_PORT/authenticate \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"mac\": \"$HNEW_MAC\", \"token\": \"TOKEN_NEW\"}'"
echo ""
echo ">>> Kết quả mong đợi trên log Controller (Khi Auth Server gọi lại Controller):"
echo "  [REST /authenticate] Granting full access for mac=00:00:00:00:00:50"
echo "  [ACLManager] REMOVING NAC rules for mac=00:00:00:00:00:50 on dpid=1"
echo ""

echo "------------------------------------------------------------"
echo "[BƯỚC 5] Xem flow table sau xác thực..."
echo ""
echo "  sudo ovs-ofctl dump-flows $SWITCH -O OpenFlow13"
echo ""
echo ">>> Kết quả mong đợi: Các luật DROP và ALLOW port 8080 cho hnew đã bị XÓA."
echo ">>> Flow table trở về trạng thái L2 Learning bình thường cho MAC này."
echo ""

echo "------------------------------------------------------------"
echo "[BƯỚC 6] Xác minh hnew đã được cấp quyền đầy đủ"
echo ""
echo "  mininet> hnew ping -c 3 $H2_IP"
echo "  >>> Kết quả mong đợi: SUCCESS (0% packet loss)"
echo ""
echo "  mininet> hnew ping -c 3 $WEBSERVER_IP"
echo "  >>> Kết quả mong đợi: SUCCESS"
echo "------------------------------------------------------------"
