#!/bin/bash
# test_scenario5.sh - Kiểm thử Kịch bản 5: NAC / Captive Portal
# Mô tả:
#   1. hnew (host mới, chưa xác thực) kết nối vào mạng
#   2. Controller mặc định chỉ cho hnew kết nối đến Auth Server (10.0.0.200:8080)
#   3. hnew truy cập Auth Server để xác thực (POST /authenticate)
#   4. Auth Server thông báo Controller cấp quyền đầy đủ
#   5. hnew có thể truy cập toàn bộ mạng

echo "[KỊCH BẢN 5: NAC / Captive Portal - Xác thực Host mới]"
echo ""

HNEW_IP="10.0.0.50"
HNEW_MAC="00:00:00:00:00:50"
AUTH_IP="10.0.0.200"
AUTH_PORT="8080"
WEBSERVER_IP="10.0.0.100"
H2_IP="10.0.0.2"
SWITCH="s1"

echo "------------------------------------------------------------"
echo "[BƯỚC 1] Gửi gói đầu tiên từ hnew để Controller phát hiện Host mới"
echo ""
echo "Trong Mininet CLI:"
echo "  mininet> hnew ping -c 1 $AUTH_IP"
echo ""
echo ">>> Controller nhận Packet-In từ MAC=$HNEW_MAC"
echo ">>> CHƯA có trong MAC table → kích hoạt NAC"
echo ">>> Controller áp luật:"
echo "    - DROP: hnew → * (tất cả traffic)"
echo "    - ALLOW: hnew → $AUTH_IP:$AUTH_PORT (TCP)"
echo "    - ALLOW: hnew DNS (UDP port 53)"
echo ""

echo "------------------------------------------------------------"
echo "[BƯỚC 2] Xác minh hnew bị hạn chế"
echo ""
echo "Trong Mininet CLI:"
echo "  mininet> hnew ping -c 3 $H2_IP"
echo "  >>> FAIL: 100% packet loss (bị DROP)"
echo ""
echo "  mininet> hnew ping -c 3 $WEBSERVER_IP"
echo "  >>> FAIL: bị DROP"
echo ""
echo "  mininet> hnew curl -s --connect-timeout 3 http://$AUTH_IP:$AUTH_PORT/health"
echo "  >>> OK: {\"status\": \"ok\"} - chỉ reach được Auth Server"
echo ""

echo "------------------------------------------------------------"
echo "[BƯỚC 3] Xem flow table - kiểm tra luật hạn chế..."
echo ""
echo "  sudo ovs-ofctl dump-flows $SWITCH -O OpenFlow13"
echo ""
echo "Tìm 2 flow entries:"
echo "  1. DROP: in_port=7, eth_src=$HNEW_MAC → actions=drop (priority=10)"
echo "  2. ALLOW: in_port=7, eth_src=$HNEW_MAC, tcp_dst=$AUTH_PORT → actions=NORMAL (priority=20)"
echo ""

echo "------------------------------------------------------------"
echo "[BƯỚC 4] hnew thực hiện xác thực qua Auth Server"
echo ""
echo "Phương án A - Gửi request trực tiếp từ hnew:"
echo "  mininet> hnew curl -s -X POST http://$AUTH_IP:$AUTH_PORT/authenticate \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"mac\": \"$HNEW_MAC\", \"token\": \"TOKEN_NEW\"}'"
echo ""
echo "Phương án B - Gửi từ máy host (chạy ngoài Mininet):"
echo "  curl -s -X POST http://$AUTH_IP:$AUTH_PORT/authenticate \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"mac\": \"$HNEW_MAC\", \"token\": \"TOKEN_NEW\"}'"
echo ""
echo "Kết quả mong đợi:"
echo '  {"authenticated": true, "mac": "00:00:00:00:00:50",'
echo '   "name": "NewHost", "message": "Welcome, NewHost! Full network access granted."}'
echo ""

echo "------------------------------------------------------------"
echo "[BƯỚC 5] Auth Server thông báo Controller (tự động)"
echo ""
echo "  Auth Server gọi: POST http://127.0.0.1:8888/authenticate"
echo "  Controller nhận → xóa flow DROP, cấp quyền đầy đủ cho MAC=$HNEW_MAC"
echo ""
echo "Xem log:"
echo "  tail -f /tmp/dynamic_acl.log | grep -E 'NAC|GRANT|ALLOWED|$HNEW_MAC'"
echo ""

echo "------------------------------------------------------------"
echo "[BƯỚC 6] Xác minh hnew đã được cấp quyền đầy đủ"
echo ""
echo "  mininet> hnew ping -c 3 $H2_IP"
echo "  >>> OK: Thành công"
echo ""
echo "  mininet> hnew ping -c 3 $WEBSERVER_IP"
echo "  >>> OK: Thành công"
echo ""
echo "  mininet> hnew curl -s http://$WEBSERVER_IP"
echo "  >>> OK: Nhận được trang web"
echo ""

echo "------------------------------------------------------------"
echo "[BƯỚC 7] Kiểm tra flow table sau xác thực..."
echo ""
echo "  sudo ovs-ofctl dump-flows $SWITCH -O OpenFlow13"
echo "  >>> Flow DROP cho hnew đã bị xóa"
echo ""

echo "------------------------------------------------------------"
echo "[BƯỚC 8] Kiểm tra REST API trạng thái NAC..."
echo ""
echo "  curl http://127.0.0.1:8888/status | python3 -m json.tool | grep -A 15 scenario5"
echo ""
echo "Xem:"
echo "  - authenticated_hosts: [\"$HNEW_MAC\"]"
echo "  - restricted_hosts:    []"
echo ""

echo "------------------------------------------------------------"
echo "Test bảo mật: Thu hồi quyền (Revoke) của hnew"
echo ""
echo "  curl -s -X POST http://$AUTH_IP:$AUTH_PORT/revoke \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"mac\": \"$HNEW_MAC\"}'"
echo ""
echo "  -> hnew bị hạn chế trở lại, cần xác thực lại"
echo "------------------------------------------------------------"
